version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules 