services:
  postgres:
    image: postgres:13
    env_file:
      - ./backend/.env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user201 -d wechat_shop"]
      interval: 5s
      timeout: 5s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development  # 使用开发阶段构建
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env.docker  # 使用Docker专用环境配置
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: ["pnpm", "run", "start:dev"]  # 开发模式启动

volumes:
  pgdata: