name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev, dev-* ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: 运行测试
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: 安装 pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10
        
    - name: 获取 pnpm store 目录
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        
    - name: 设置 pnpm 缓存
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: 安装依赖
      run: pnpm install --frozen-lockfile
      
    - name: 代码检查 (ESLint)
      run: pnpm run lint
      
    - name: 运行单元测试
      run: pnpm run test:unit:run
      
    - name: 构建项目
      run: pnpm run build
      
    - name: 上传测试覆盖率报告
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-coverage
        path: coverage/
        retention-days: 7

  e2e-tests:
    name: 端到端测试
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: 安装 pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10
        
    - name: 安装依赖
      run: pnpm install --frozen-lockfile
      
    - name: 安装 Playwright 浏览器
      run: pnpm exec playwright install --with-deps
      
    - name: 运行 Playwright 测试
      run: pnpm run test
      
    - name: 上传 Playwright 报告
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30 